### ISSUE TITLE
problem make

### ISSUE THREAD

**Issue by oremic** [cduvenhorst/sonoff-s20-homekit#2]
AR build/wifi_config.a
Linking OTA firmware for slot 1
Linking OTA firmware for slot 0
LD build/sonoff-s20.out
Building OTA firmware images
FW firmware/sonoff-s20.bin
make: quiet: No such file or directory
make: [ota-images] Error 1 (ignored)
/bin/sh: ./firmware/ota/sonoff-s20_2_0.bin: No such file or directory
make: *** [ota-images] Error 1
make: *** Waiting for unfinished jobs....

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
install esptool2 and openssl, it fixed this error for me
